apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-minio
  labels:
    app: {{ .Release.Name }}
    component: minio
spec:
  accessModes:
    - {{ .Values.minio.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  storageClassName: {{ .Values.minio.persistence.storageClassName }}