apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.minio.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  storageClassName: {{ .Values.minio.persistence.storageClassName }}