apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  host: {{ .Values.minio.host | quote }}
  port:
    targetPort: minio
  to:
    kind: Service
    name: {{ include "minio.fullname" . }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect