"""
Database tables and data access functions for Wally Data Layer Meta Information
"""
from sqlalchemy.orm import Session, load_only
from sqlalchemy.sql import select
from sqlalchemy import func, text
from geojson import Feature, Point, FeatureCollection
from logging import getLogger
from app.geocoder.db_models import geocode
from shapely.geometry import Point
from shapely import wkt
from geoalchemy2.elements import WKTElement

logger = getLogger("geocoder")


def lookup_by_text(db: Session, query: str):
    """ look up features by text (e.g. name, an ID number), returning geojson """

    # query the geocode materialized view, using the tsv column (generated by to_tsvector i.e. text search vector).
    # adding :* indicates prefix matching (partial matches for beginning of word)
    # plainto_tsquery is similar to to_tsquery but allows spaces.
    q = select([geocode]) \
        .where(text("tsv @@ plainto_tsquery(:query)")) \
        .order_by(func.ts_rank('tsv', func.plainto_tsquery(f"{query}:*"))) \
        .limit(5)

    features = []

    for row in db.execute(q, {"query": query}):
        # parse center point coordinate, which comes in a ST_AsText (wkt) column.
        point = wkt.loads(row.center)

        # add the Point to make a valid geojson Feature, but also add a "center" property
        # in [lat, lng] format for the web geocoder.
        feat = Feature(geometry=point)
        feat['center'] = [point.x, point.y]

        # formatted name for geocoder dropdown options
        feat['place_name'] = f"{row.kind}: {row.primary_id} - {row.name}"
        feat['place_type'] = row.kind
        features.append(feat)

    fc = FeatureCollection(features)
    return fc
