{{- if .Values.matomo.enabled }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "matomo.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-admin
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.matomo.adminUser | quote }}
  password: {{ if $existing }}{{ index $existing.data "password" | b64dec | quote }}{{ else }}{{ .Values.matomo.adminPassword | default (randAlphaNum 16) | quote }}{{ end }}
{{- end }}