ARG DOCKER_TAG=latest

FROM --platform=linux/amd64 rust:1.67.1 AS builder
# FROM --platform=linux/amd64 rust:latest AS builder

RUN apt-get update && apt-get install -y musl-tools librust-atk-dev libgtk-3-dev git && \
  rustup target add x86_64-unknown-linux-musl && \
  git clone https://github.com/jblindsay/whitebox-tools.git /wbt
  # NOTE: this branch no longer exists
  # && cd /wbt && git checkout d8_flow_accum-fix

WORKDIR /wbt

RUN cargo clean
RUN cargo build --release 