FROM --platform=linux/amd64 artifacts.developer.gov.bc.ca/wd1b-wbt-docker-local/wbt-rust:1.0 as builder

FROM --platform=linux/amd64 python:3.7

COPY --from=builder /wbt/target/release/whitebox_tools /usr/local/bin/

WORKDIR /app/

RUN useradd wally -M -G root -u 1021 && chmod -R 775 /app \
  && chown -R wally:root /app \
  && apt-get update && apt-get -y install ca-certificates libgdal-dev gdal-bin

RUN pip install pygdal=="`gdal-config --version`.*"

COPY ./requirements.txt.dev /

RUN pip install -r /requirements.txt.dev

COPY . /app
ENV PYTHONPATH=/app
COPY --from=builder /wbt/whitebox_tools.py /app/

RUN pytest /app/tests/ -W ignore::DeprecationWarning

EXPOSE 8000
USER 1021

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Uvicorn
CMD ["/app/start.sh"]
