-- BC MEAN ANNUAL FLOWS
select ANNUAL_STATISTICS.STATION_NUMBER, ANNUAL_STATISTICS.YEAR, 
ANNUAL_STATISTICS.MEAN, ANNUAL_STATISTICS."MIN", ANNUAL_STATISTICS."MAX",
ANNUAL_STATISTICS.MIN_MONTH, ANNUAL_STATISTICS.MAX_MONTH, 
STATIONS.LATITUDE, STATIONS.LONGITUDE, STATIONS.DRAINAGE_AREA_GROSS, STATIONS.HYD_STATUS
from ANNUAL_STATISTICS JOIN STATIONS on ANNUAL_STATISTICS.STATION_NUMBER = STATIONS.STATION_NUMBER
where STATIONS.PROV_TERR_STATE_LOC = 'BC'
and ANNUAL_STATISTICS.MEAN is not NULL;