{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
{{- end }}