"""add stream table2

Revision ID: 1d3a9bfe6150
Revises: ab7b5daedfbd
Create Date: 2019-11-13 23:00:16.396897

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d3a9bfe6150'
down_revision = 'ab7b5daedfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fwa_stream_networks',
                    sa.Column('ogc_fid', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('linear_feature_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('watershed_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('edge_type', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('blue_line_key', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('watershed_key', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('fwa_watershed_code', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('local_watershed_code', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('watershed_group_code', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('downstream_route_measure', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('length_metre', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('feature_source', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('gnis_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('gnis_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('left_right_tributary', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('stream_order', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('stream_magnitude', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('waterbody_key', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('blue_line_key_50k', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('watershed_code_50k', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('watershed_key_50k', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('watershed_group_code_50k', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('gradient', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('feature_code', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('objectid', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('se_anno_cad_data', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('feature_length_m', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('geometry.len', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('fme_feature_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('ogc_fid', name='fwa_stream_networks_pkey')
                    )
    op.create_index('fwa_stream_networks_geom_geom_idx', 'fwa_stream_networks', ['geom'], unique=False)

    # add metadata for this layer.
    op.execute('SET search_path TO metadata')
    op.execute("""
    WITH vc_id AS (
                INSERT INTO vector_catalogue (
                description, 
                vector_name,
                create_user, create_date, update_user, update_date, effective_date, expiry_date
            ) VALUES (
                'Freshwater Atlas Stream Networks', 
                'fwa_stream_networks',
                'ETL_USER', CURRENT_DATE, 'ETL_USER', CURRENT_DATE, CURRENT_DATE, '9999-12-31T23:59:59Z'
            ) RETURNING vector_catalogue_id
        ),

        ds_id AS (
            INSERT INTO data_source (
                data_format_code,
                name,
                description,
                source_url,
                source_object_name,
                data_table_name,
                source_object_id,
                create_user, create_date, update_user, update_date, effective_date, expiry_date
            ) VALUES (
                'json',
                'Freshwater Atlas Stream Networks',
                'Flow network arcs (observed, inferred and constructed). Contains no banks, coast or watershed bourdary arcs. Directionalized and connected. Contains heirarchial key and route identifier.',
                'https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-stream-network',
                'WHSE_BASEMAPPING.FWA_STREAM_NETWORKS_SP',
                'fwa_stream_networks',
                'LINEAR_FEATURE_ID',
                'ETL_USER', CURRENT_DATE, 'ETL_USER', CURRENT_DATE, CURRENT_DATE, '9999-12-31T23:59:59Z'
            ) RETURNING data_source_id
        )

        INSERT INTO display_catalogue (
            display_data_name,
            display_name,
            label_column,
            label,
            highlight_columns,
            vector_catalogue_id,
            data_source_id,
            layer_category_code,
            mapbox_layer_id,
            create_user, create_date, update_user, update_date, effective_date, expiry_date
        ) VALUES (
            'fwa_stream_networks',
            'Freshwater Atlas Stream Networks',
            'LINEAR_FEATURE_ID',
            'Feature ID',
            ARRAY[
                'stream_order', 'stream_magnitude', 'feature_length_m', 'watershed_group_id'
            ],
            vc_id,
            ds_id,
            'FRESHWATER_MARINE',
            '',
            'ETL_USER', CURRENT_DATE, 'ETL_USER', CURRENT_DATE, CURRENT_DATE, '9999-12-31T23:59:59Z'
        );
    """)

    op.execute('SET search_path TO public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
