"""pg_fasstr functions

Revision ID: bc8bc4bb72cb
Revises: bb906a00fbe7
Create Date: 2021-05-19 12:49:30.018297

How to populate fasstr_flows from existing HYDAT data:


  with flows as (
    select
      f.station_number,
      year,
      month,
      flow1,
      flow2,
      flow3,
      flow4,
      flow5,
      flow6,
      flow7,
      flow8,
      flow9,
      flow10,
      flow11,
      flow12,
      flow13,
      flow14,
      flow15,
      flow16,
      flow17,
      flow18,
      flow19,
      flow20,
      flow21,
      flow22,
      flow23,
      flow24,
      flow25,
      flow26,
      flow27,
      flow28,
      flow29,
      flow30,
      flow31
    from hydat.dly_flows f
    inner join hydat.stations s on s.station_number = f.station_number
    where s.prov_terr_state_loc = 'BC'
  ),
  kv as (
    select station_number, year, month, each(hstore(flows)) as kv from flows
  )
  insert into hydat.fasstr_flows (station_number, date, value)
  select
    station_number,
    to_date(concat(year::text, lpad(month::text, 2, '0'), lpad(replace((kv).key, 'flow', '')::text, 2, '0')), 'YYYYMMDD') as date,
    (kv).value::numeric as value
  from kv where (kv).key like 'flow%' and (kv).value is not null;


"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc8bc4bb72cb'
down_revision = 'bb906a00fbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('longterm_stats',
                    sa.Column('month', sa.Text(), nullable=False),
                    sa.Column('mean', sa.Numeric(), nullable=True),
                    sa.Column('median', sa.Numeric(), nullable=True),
                    sa.Column('maximum', sa.Numeric(), nullable=True),
                    sa.Column('minimum', sa.Numeric(), nullable=True),
                    sa.Column('p10', sa.Numeric(), nullable=True),
                    sa.Column('p90', sa.Numeric(), nullable=True),
                    sa.PrimaryKeyConstraint('month'),
                    schema='hydat'
                    )
    op.create_table('fasstr_flows',
                    sa.Column('fasstr_flows_id', sa.Integer(), primary_key=True, nullable=False),
                    sa.Column('station_number', sa.Text(), nullable=False, index=True),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('value', sa.Numeric(), nullable=True),
                    sa.ForeignKeyConstraint(['station_number'], ['hydat.stations.station_number'], ),
                    sa.PrimaryKeyConstraint('fasstr_flows_id'),
                    schema='hydat'
                    )

    dirname = os.path.dirname(__file__)
    filename = os.path.join(dirname, 'sql/20210519124930_fasstr_functions.sql')
    with open(filename, "r") as r:
        fasstr_funcs = r.read()
    op.execute(fasstr_funcs)


def downgrade():

    op.execute("""
        drop function if exists hydat.r_fasstr_calc_annual_lowflows;
        drop function if exists hydat.fasstr_calc_annual_lowflows(date[], numeric[], boolean);
        drop function if exists hydat.fasstr_calc_annual_lowflows(text, boolean);

        drop function if exists hydat.fasstr_calc_longterm_daily_stats(date[], numeric[], boolean, boolean);
        drop function if exists hydat.fasstr_calc_longterm_daily_stats(text, boolean, boolean);

        drop function if exists hydat.fasstr_compute_frequency_quantile(date[], numeric[], integer, integer, boolean, boolean);
        drop function if exists hydat.fasstr_compute_frequency_quantile(text, integer, integer, boolean, boolean);
    """)
    op.drop_table('fasstr_flows', schema='hydat')
    op.drop_table('longterm_stats', schema='hydat')

    # ### end Alembic commands ###
