"""update wells metadata

Revision ID: 40a169a3bda1
Revises: db6313a85cf5
Create Date: 2019-12-19 23:11:37.323132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40a169a3bda1'
down_revision = 'db6313a85cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    q = """
        UPDATE  metadata.display_catalogue
        SET     label_column = 'well_tag_number'
        WHERE   display_data_name = 'groundwater_wells'
    """
    op.execute(q)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
