"""create prism schema

Revision ID: 47f2e019d65d
Revises: aaffa7e117fb
Create Date: 2020-04-14 20:46:40.765727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47f2e019d65d'
down_revision = 'aaffa7e117fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    create schema if not exists prism;
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute("""
    drop schema prism;
    """)
    return
