"""add search table

Revision ID: 4afd09e628a3
Revises: 27df43577da2
Create Date: 2019-09-08 19:43:55.577419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4afd09e628a3'
down_revision = '27df43577da2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE MATERIALIZED VIEW geocode_lookup AS

        SELECT ST_AsText(stn.geom) as center, stn.station_number as primary_id, to_tsvector(concat_ws(' ',stn.station_number, stn.station_name)) as tsv, 'stream-station' as kind
        FROM hydat.stations AS stn
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
