"""add search table

Revision ID: 4afd09e628a3
Revises: 27df43577da2
Create Date: 2019-09-08 19:43:55.577419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4afd09e628a3'
down_revision = '8e74234b8872'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
