"""watershed_cache

Revision ID: 5928512ce14d
Revises: f2b445f6650c
Create Date: 2020-03-04 00:18:52.846245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '5928512ce14d'
down_revision = 'f2b445f6650c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upstream_watershed_cache',
                    sa.Column('upstream_watershed_cache_id', sa.Integer(), primary_key=True,
                              comment='upstream_watershed_cache_id is the primary key for watershed cache records'),
                    sa.Column('watershed_feature_id', sa.Integer(), comment='watershed_feature_id represents the base '
                              'feature/polygon from the Freshwater Atlas Watersheds that we want to find features upstream of.'),
                    sa.Column('include_features', sa.Integer(), nullable=True,
                              comment='additional features included in this polygon'),
                    sa.Column('geom', Geometry('GEOMETRY', 4326),
                              comment='The cached Polygon geometry.'),
                    sa.Column('create_date', sa.DateTime(),
                              comment='Date that this cache record was created.'),
                    sa.Column('update_date', sa.DateTime(),
                              comment='Date that this cache record was updated'),
                    sa.Column('expiry_date', sa.DateTime(),
                              comment='Date that this cache record should expire'),
                    )
    op.create_index('upstream_watershed_cache_unique_idx', 'upstream_watershed_cache', [
                    'watershed_feature_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
