"""update srids

Revision ID: 6d8fb3e81c4a
Revises: 30d75d8eb63d
Create Date: 2019-10-23 23:29:04.279822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d8fb3e81c4a'
down_revision = '30d75d8eb63d'
branch_labels = None
depends_on = None


def upgrade():
    # uppercase column name arguments for the UpdateGeometrySRID function
    # don't need double quotes like usual
    op.execute("""SELECT UpdateGeometrySRID('bc_major_watersheds', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('bc_wildfire_active_weather_stations', 'SHAPE', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('cadastral', 'SHAPE', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('ecocat_water_related_reports', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('freshwater_atlas_stream_directions', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('freshwater_atlas_watersheds', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('ground_water_aquifers', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('ground_water_wells', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('water_allocation_restrictions', 'GEOMETRY', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('water_rights_licenses', 'SHAPE', 4326)""")
    op.execute("""SELECT UpdateGeometrySRID('critical_habitat_species_at_risk', 'SHAPE', 4326)""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
