"""set wms_style to non nullable

Revision ID: 77ba24335c15
Revises: 207b3b1622b8
Create Date: 2020-01-07 18:47:48.879507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77ba24335c15'
down_revision = '207b3b1622b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        update metadata.wms_catalogue set wms_style='' where wms_style is null;
        alter table metadata.wms_catalogue alter column wms_style set not null;
        alter table metadata.wms_catalogue alter column wms_style set default '';
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
