"""change pk for applications

Revision ID: 7fa8f38196e4
Revises: c0266f14f5e6
Create Date: 2019-11-15 23:26:12.825231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa8f38196e4'
down_revision = 'a2b8d50d796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table water_rights_applications drop constraint water_rights_applications_pkey;
    alter table water_rights_applications alter column "WLS_WRA_SYSID" set data type varchar;
    alter table water_rights_applications add constraint water_rights_applications_pkey primary key ("WLS_WRA_SYSID");
    """)

    op.execute(
        """
        SELECT UpdateGeometrySRID('water_rights_applications', 'SHAPE', 4326);
        SELECT UpdateGeometrySRID('automated_snow_weather_station_locations', 'SHAPE', 4326);""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
