"""

Revision ID: 8f0eb2b03a97
Revises: a6cb8a361392
Create Date: 2020-06-08 17:34:00.915029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f0eb2b03a97'
down_revision = 'a6cb8a361392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    
    
    
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
