"""

Revision ID: 8f0eb2b03a97
Revises: a6cb8a361392
Create Date: 2020-06-08 17:34:00.915029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f0eb2b03a97'
down_revision = 'a6cb8a361392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""

    alter table metadata.data_source
    alter column name type varchar(200);


    update  metadata.wms_catalogue
    set     description = 'ParcelMap BC'
    where   description = 'ParcelMap BC Parcel Fabric';

    update  metadata.wms_catalogue
    set     description = 'Critical Habitat (federally-listed species at risk)'
    where   description = 'Critical Habitat federally-listed species at risk';

    update  metadata.wms_catalogue
    set     description = 'Known BC Fish Observations & Distributions'
    where   description = 'Known BC Fish Observations & BC Fish Distributions';
    
    update  metadata.layer_category
    set     description = 'Forests, Grasslands, and Wetlands'
    where   description = 'Forests, Grasslands and Wetlands';



    update  metadata.display_catalogue
    set     display_name = 'Critical Habitat (federally-listed species at risk)'
    where   display_name = 'Critical Habitat for federally-listed species at risk (posted)';

    update  metadata.display_catalogue
    set     display_name = 'EcoCat Water-related Reports'
    where   display_name = 'Ecocat - Water related reports';

    update  metadata.display_catalogue
    set     display_name = 'Hydrometric Stream Flow (HYDAT)'
    where   display_name = 'Hydrometric Stream Flow';

    update  metadata.display_catalogue
    set     display_name = 'Known BC Fish Observations & Distributions'
    where   display_name = 'Known BC Fish Observations and BC Fish Distributions';




    update  metadata.data_source
    set     name = 'Known BC Fish Observations & Distributions'
    where   name = 'Known BC Fish Observations and BC Fish Distributions';

    update  metadata.data_source
    set     name = 'EcoCat Water-related Reports'
    where   name = 'Ecocat - Water related reports';

    update  metadata.data_source
    set     name = 'Critical Habitat (federally-listed species at risk)'
    where   name = 'Critical Habitat for federally-listed species at risk (posted)';

    update  metadata.data_source
    set     name = 'ParcelMap BC'
    where   name = 'ParcelMap BC Parcel Fabric';
    

    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
