"""add geom column

Revision ID: a42005339c3b
Revises: 88f4ca055ae7
Create Date: 2019-08-12 22:38:59.667933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a42005339c3b'
down_revision = '88f4ca055ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    alter table hydat.stations add column
        geom geometry('POINT', 4326);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
