"""add table for mapbox sources

Revision ID: c0266f14f5e6
Revises: 1d3a9bfe6150
Create Date: 2019-11-15 20:20:24.603138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0266f14f5e6'
down_revision = '7fa8f38196e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapbox_source',
                    sa.Column('create_user', sa.String(length=100), nullable=True,
                              comment='The user who created this record in the database.'),
                    sa.Column('create_date', sa.DateTime(
                    ), nullable=True, comment='Date and time (UTC) when the physical record was created in the database.'),
                    sa.Column('update_user', sa.String(length=100), nullable=True,
                              comment='The user who last updated this record in the database.'),
                    sa.Column('update_date', sa.DateTime(), nullable=True,
                              comment='Date and time (UTC) when the physical record was updated in the database. It will be the same as the create_date until the record is first updated after creation.'),
                    sa.Column('effective_date', sa.DateTime(
                    ), nullable=True, comment='The date and time that the code became valid and could be used.'),
                    sa.Column('expiry_date', sa.DateTime(
                    ), nullable=True, comment='The date and time after which the code is no longer valid and should not be used.'),
                    sa.Column('mapbox_source_id', sa.String(), nullable=False),
                    sa.Column('max_zoom', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('mapbox_source_id'),
                    schema='metadata'
                    )
    op.add_column('display_catalogue',
                  sa.Column('mapbox_source_id', sa.String(), nullable=True),
                  schema='metadata'
                  )
    op.create_foreign_key(
        'fk_display_catalogue_mapbox_source_id',
        'display_catalogue', 'mapbox_source',
        ['mapbox_source_id'], ['mapbox_source_id'], source_schema="metadata", referent_schema="metadata"
    )

    op.execute("""
        INSERT INTO metadata.mapbox_source (mapbox_source_id, max_zoom) VALUES
        ('iit-water.2svbut5f', 9),
        ('iit-water.7iwr3fo1', NULL),
        ('iit-water.0tsq064k', NULL),
        ('iit-water.36r1x37x', NULL),
        ('iit-water.2ah76e1a', NULL),
        ('iit-water.6q8q0qac', NULL);
    """)

    op.execute("""
        UPDATE metadata.display_catalogue SET mapbox_layer_id='iit-water.6q8q0qac' WHERE mapbox_layer_id='iit-water.fwa-streams';
        UPDATE metadata.display_catalogue SET mapbox_source_id=mapbox_layer_id WHERE mapbox_layer_id != '';
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapbox_source', schema='metadata')
    op.drop_constraint('fk_display_catalogue_mapbox_source_id', 'display_catalogue')
    op.drop_column('display_catalogue',
                   'mapbox_source_id')
    # ### end Alembic commands ###
