apiVersion: v2
name: wally-importer
description: Jobs for importing our test/production databases
icon: https://www.nicepng.com/png/detail/521-5211827_bc-icon-british-columbia-government-logo.png
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Liam Franke
    email: liam@foundryspatial.com
