global:
  environment: DEV
  databaseSuperUser: postgres
  databaseApplicationUser: wally
  databaseAlias: pg-e5a12179-crunchy
importer:
  image: "ghcr.io/bcgov/wally/imports:latest"
  minioHostUrl: http://wally-staging-minio:9000
  downloadJobs:
    - jobName: "wells"
      layerName: "ground_water_wells"
      downloadLink: "https://apps.nrs.gov.bc.ca/gwells/api/v2/gis/wells"
  importJobs:
    - jobName: "applications"
      layerName: "water_rights_applications"
    - jobName: "licences"
      layerName: "water_rights_licenses"
    - jobName: "wells"
      layerName: "ground_water_wells"
    - jobName: "snow"
      layerName: "automated_snow_weather_station_locations"
    - jobName: "wildfire"
      layerName: "bc_wildfire_active_weather_stations"
    - jobName: "ecocat"
      layerName: "ecocat_water_related_reports"
    - jobName: "aquifers"
      layerName: "ground_water_aquifers"
    - jobName: "fncommunities"
      layerName: "fn_community_locations"
    - jobName: "fntreatyareas"
      layerName: "fn_treaty_areas"
    - jobName: "fntreatylands"
      layerName: "fn_treaty_lands"
    - jobName: "isolines"
      layerName: "normal_annual_runoff_isolines"
  mapboxUploadJobs:
    - jobName: "first-nations"
      layerName: "iit-water.first-nations"
    - jobName: "0tsq064k"
      layerName: "iit-water.0tsq064k"
    - jobName: "448thhpa"
      layerName: "iit-water.448thhpa"
  tileJobs:
    - jobName: "aquifers"
      layerName: "aquifers"
    - jobName: "licences"
      layerName: "water_rights_licenses"
    - jobName: "wells"
      layerName: "ground_water_wells"
    - jobName: "snow"
      layerName: "automated_snow_weather_station_locations"
    - jobName: "bcmajorwatersheds"
      layerName: "bc_major_watersheds"
    - jobName: "wildfire"
      layerName: "bc_wildfire_active_weather_stations"
    - jobName: "criticalhabitat"
      layerName: "critical_habitat_species_at_risk"
    - jobName: "ecocat"
      layerName: "ecocat_water_related_reports"
    - jobName: "hydrozones"
      layerName: "hydrologic_zone_boundaries"
    - jobName: "applications"
      layerName: "water_rights_applications"
    - jobName: "fncommunities"
      layerName: "fn_community_locations"
    - jobName: "fntreatyareas"
      layerName: "fn_treaty_areas"
    - jobName: "fntreatylands"
      layerName: "fn_treaty_lands"
    - jobName: "glaciers"
      layerName: "freshwater_atlas_glaciers"
    - jobName: "isolines"
      layerName: "normal_annual_runoff_isolines"
    - jobName: "fishobservations"
      layerName: "fish_observations"
    - jobName: "waterapprovalpoints"
      layerName: "water_approval_points"
  wfsJobs:
    - jobName: "licences"
      layerName: "water_rights_licenses"
    - jobName: "snow"
      layerName: "automated_snow_weather_station_locations"
    - jobName: "wildfire"
      layerName: "bc_wildfire_active_weather_stations"
    - jobName: "ecocat"
      layerName: "ecocat_water_related_reports"
    - jobName: "aquifers"
      layerName: "ground_water_aquifers"
    - jobName: "hydrozones"
      layerName: "hydrologic_zone_boundaries"
    - jobName: "applications"
      layerName: "water_rights_applications"
    - jobName: "fncommunities"
      layerName: "fn_community_locations"
    - jobName: "fntreatyareas"
      layerName: "fn_treaty_areas"
    - jobName: "fntreatylands"
      layerName: "fn_treaty_lands"
    - jobName: "glaciers"
      layerName: "freshwater_atlas_glaciers"
    - jobName: "waterapprovalpoints"
      layerName: "water_approval_points"
    - jobName: "bcmajorwatersheds"
      layerName: "bc_major_watersheds"
  prismJobs:
    - datasetName: "pr"