export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS'
export const SEARCH_WELLS = 'SEARCH_WELLS'
export const FETCH_WELL_LOCATIONS = 'FETCH_WELL_LOCATIONS'
export const FETCH_DATA_SOURCES = 'FETCH_DATA_SOURCES'
export const FETCH_MAP_OBJECTS = 'FETCH_MAP_OBJECTS'
export const CLEAR_MAP_SELECTIONS = 'CLEAR_MAP_SELECTIONS'
export const SELECT_SINGLE_MAP_OBJECT = 'SELECT_SINGLE_MAP_OBJECT'

