export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS'
export const SEARCH_WELLS = 'SEARCH_WELLS'
export const FETCH_WELL_LOCATIONS = 'FETCH_WELL_LOCATIONS'
export const FETCH_DATA_SOURCES = 'FETCH_DATA_SOURCES'

