export const SET_SEARCH_BOUNDS = 'SET_SEARCH_BOUNDS';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SET_SEARCH_RESULT_FILTERS = 'SET_SEARCH_RESULT_FILTERS';
export const SET_LOCATION_SEARCH_RESULTS = 'SET_LOCATION_SEARCH_RESULTS';
export const SET_DATA_SOURCES = 'SET_DATA_SOURCES';
export const SET_MAP_LAYER_STATE = 'SET_MAP_LAYER_STATE';
export const SET_MAP_OBJECT_SELECTIONS = 'SET_MAP_OBJECT_SELECTIONS'