# Source: wally-backup-restore/templates/psql.backup.job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: dump-psql-2026-08-19
  namespace: d1b5d2-prod
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        role: dump-psql
    spec:
      restartPolicy: Never
      containers:
        - name: dump-psql
          image: "ghcr.io/bcgov/wally/backup-restore:latest"
          imagePullPolicy: Always
          command: ["python3", "psql/backup.py"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wally-psql-backup-restore-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: wally-psql-backup-restore-credentials
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wally-psql-backup-restore-credentials
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wally-psql-backup-restore-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wally-psql-backup-restore-credentials
                  key: password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: secret_key
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: bucket
            - name: AWS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: s3-secrets
                  key: endpoint
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi