{{- if .Values.mariadb.enabled }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "mariadb.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-root-password: {{ if $existing }}{{ index $existing.data "database-root-password" | b64dec | quote }}{{ else }}{{ randAlphaNum 16 | quote }}{{ end }}
  database-password: {{ if $existing }}{{ index $existing.data "database-password" | b64dec | quote }}{{ else }}{{ randAlphaNum 10 | quote }}{{ end }}
  database-user: {{ if $existing }}{{ index $existing.data "database-user" | b64dec | quote }}{{ else }}{{ randAlphaNum 10 | quote }}{{ end }}
  database-name: {{ .Values.mariadb.database | quote }}
{{- end }}