{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-uri: 'mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}'
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
{{- end }}