-- BC DLY MONTHLY FLOWS (full months only)
select DLY_FLOWS.STATION_NUMBER, DLY_FLOWS."YEAR", DLY_FLOWS."MONTH", 
DLY_FLOWS.NO_DAYS, DLY_FLOWS.MONTHLY_MEAN, DLY_FLOWS.MONTHLY_TOTAL, DLY_FLOWS."MIN", DLY_FLOWS."MAX", 
STATIONS.DRAINAGE_AREA_GROSS, STATIONS.DRAINAGE_AREA_EFFECT, STATIONS.LATITUDE, STATIONS.LONGITUDE
from DLY_FLOWS JOIN STATIONS on DLY_FLOWS.STATION_NUMBER = STATIONS.STATION_NUMBER
where DLY_FLOWS.FULL_MONTH = 1
and DLY_FLOWS.MONTHLY_MEAN is not NULL and DLY_FLOWS."MONTH" = 12
and STATIONS.PROV_TERR_STATE_LOC = 'BC';

-- BC STATION LOCATIONS
select STATION_NUMBER, LATITUDE, LONGITUDE
from STATIONS where PROV_TERR_STATE_LOC = 'BC';


select count(DISTINCT STATION_NUMBER) from STATIONS where PROV_TERR_STATE_LOC = 'BC';
SELECT count(*) from STATIONS where PROV_TERR_STATE_LOC = 'BC';
