---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-openshift-ingress-to-frontend
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-backend-to-db
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: {{ .Values.global.databaseAlias }}
  ingress:
    - ports:
        - protocol: TCP
          port: 5432
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "backend.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-frontend-to-backend
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "frontend.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-backend-to-minio
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
    - ports:
        - protocol: TCP
          port: 9000
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "backend.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress