const mapData = {
  WMS_AQUIFERS: 'WHSE_WATER_MANAGEMENT.GW_AQUIFERS_CLASSIFICATION_SVW',
  WMS_WATER_RIGHTS_LICENCES: 'WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_LICENCES_SV',
  WMS_GROUNDWATER_LICENCES: 'WHSE_WATER_MANAGEMENT.WLS_PWD_LICENCES_SVW',
  WMS_WATERSHEDS: 'WHSE_BASEMAPPING.FWA_WATERSHEDS_POLY',
  HYDAT: 'HYDAT'
};

export default mapData;
