from api.config import RASTER_FILE_DIR

PRECIP_RASTER = f"{RASTER_FILE_DIR}/NORM_6190_Precip.tif"
PET_RASTER_V2 = f"{RASTER_FILE_DIR}/WNA_et0.tif"
PET_RASTER_V1 = f"{RASTER_FILE_DIR}/WNA_et0_v1.tif"
CDEM_FILE = f"{RASTER_FILE_DIR}/Burned_CDEM_4326.tif"
SRTM_FILE = f"{RASTER_FILE_DIR}/Burned_SRTM_3005.tif"
