# Remote Ref Deprecated Early September 2026, removing from build, using previously built version.

FROM artifacts.developer.gov.bc.ca/docker-remote/minio/minio:latest

COPY ./minio-entrypoint.sh /
ENTRYPOINT /minio-entrypoint.sh