{
 "title": "Wally Staging",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Gatekeeper",
   "type": "gauge",
   "description": "Number of Gatekeeper replicas currently reporting metrics.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{name=\"wally-staging-gatekeeper\"})"
    }
   ]
  },
  {
   "title": "Gatekeeper HTTP status codes",
   "type": "graph",
   "description": "Gatekeeper HTTP status codes over a 10 minute period",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(proxy_request_status_total[10m])",
     "legendFormat": "{{kubernetes_pod_name}} [code={{code}}]"
    }
   ]
  },
  {
   "title": "Gatekeeper latency",
   "type": "graph",
   "description": "Latency of requests proxied by Gatekeeper",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxy_request_duration_sec",
     "legendFormat": "{{kubernetes_pod_name}} [quantile={{quantile}}]"
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "gauge",
   "description": "Number of NGINX pods reporting metrics",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(up{deploymentconfig=\"wally-staging-frontend\"})"
    }
   ]
  },
  {
   "title": "NGINX requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_requests_total[10m])",
     "legendFormat": "{{kubernetes_pod_name}} [code={{code}}]"
    }
   ]
  },
  {
   "title": "Request duration (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds*1000",
     "legendFormat": "{{kubernetes_pod_name}} quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(up{statefulset=\"wally-psql-staging\"})"
    }
   ]
  },
  {
   "title": "pg_stat_activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count) by(statefulset_kubernetes_io_pod_name)",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    },
    {
     "expr": "min(pg_settings_max_connections)",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "API automated monitoring (requests/errors last 60 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apitest_requests_errors_total{path!~\".*no...value.*\"}[60m])) by (name, path)",
     "legendFormat": "[errors] {{ path }}"
    },
    {
     "expr": "sum(increase(apitest_requests_total{path!~\".*no...value.*\"}[60m])) by (name, path)",
     "legendFormat": "[requests] {{ path }}"
    }
   ]
  }
 ]
}