apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: loki-template
metadata:
  annotations:
  name: loki-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${LOKI_SERVICE_NAME}
      labels:
        app: ${LOKI_SERVICE_NAME}
        chart: loki-0.8.4
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
    data:
      loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xvb2tfYmFja19wZXJpb2Q6IDAKaW5nZXN0ZXI6CiAgY2h1bmtfYmxvY2tfc2l6ZTogMjYyMTQ0CiAgY2h1bmtfaWRsZV9wZXJpb2Q6IDE1bQogIGxpZmVjeWNsZXI6CiAgICByaW5nOgogICAgICBrdnN0b3JlOgogICAgICAgIHN0b3JlOiBpbm1lbW9yeQogICAgICByZXBsaWNhdGlvbl9mYWN0b3I6IDEKbGltaXRzX2NvbmZpZzoKICBlbmZvcmNlX21ldHJpY19uYW1lOiBmYWxzZQpzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgLSBmcm9tOiAyMDE4LTA0LTE1CiAgICBpbmRleDoKICAgICAgcGVyaW9kOiAxNjhoCiAgICAgIHByZWZpeDogaW5kZXhfCiAgICBvYmplY3Rfc3RvcmU6IGZpbGVzeXN0ZW0KICAgIHNjaGVtYTogdjkKICAgIHN0b3JlOiBib2x0ZGIKc2VydmVyOgogIGh0dHBfbGlzdGVuX3BvcnQ6IDMxMDAKc3RvcmFnZV9jb25maWc6CiAgYm9sdGRiOgogICAgZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2luZGV4CiAgZmlsZXN5c3RlbToKICAgIGRpcmVjdG9yeTogL2RhdGEvbG9raS9jaHVua3MKdGFibGVfbWFuYWdlcjoKICByZXRlbnRpb25fZGVsZXRlc19lbmFibGVkOiBmYWxzZQogIHJldGVudGlvbl9wZXJpb2Q6IDAK
    # Source: loki/templates/service.yaml
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: promtail-config
      labels:
        app: ${LOKI_SERVICE_NAME}
        chart: loki-0.8.4
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
    data:
      promtail.yaml: |
        scrape_configs:
        - job_name: system          
          entry_parser: raw          
          static_configs:
            - targets:
                - localhost
              labels:
                job: wally               
                my-label: test              
                __path__: /app/.log/access.log
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${LOKI_SERVICE_NAME}
      labels:
        app: ${LOKI_SERVICE_NAME}
        chart: loki-0.8.4
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
      annotations:
        {}
    spec:
      type: ClusterIP
      ports:
        - port: 3100
          protocol: TCP
          name: http-metrics
          targetPort: http-metrics
      selector:
        app: ${LOKI_SERVICE_NAME}
        release: ${LOKI_SERVICE_NAME}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${LOKI_SERVICE_NAME}
      labels:
        app: monitoring
        name: ${LOKI_SERVICE_NAME}
        chart: loki-0.8.4
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
      annotations:
        {}
    spec:
      replicas: 1
      minReadySeconds: 0
      selector:
        matchLabels:
          app: ${LOKI_SERVICE_NAME}
          release: ${LOKI_SERVICE_NAME}
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: monitoring
            name: ${LOKI_SERVICE_NAME}
            chart: loki-0.8.4
            release: ${LOKI_SERVICE_NAME}
          annotations:
            checksum/config: ead7f72a64861d8011338b7b455e4cea4ff355aa3baa2b8f8394e2191bc3b9b0
            prometheus.io/port: http-metrics
            prometheus.io/scrape: "true"
            
        spec:
          serviceAccountName: default
          containers:
            - name: ${LOKI_SERVICE_NAME}
              image: "grafana/loki:latest"
              imagePullPolicy: Always
              args:
                - "-config.file=/etc/loki/loki.yaml"            
              volumeMounts:
                - name: config
                  mountPath: /etc/loki
                - name: storage
                  mountPath: "/data"
                  subPath: ""
              ports:
                - name: http-metrics
                  containerPort: 3100
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /ready
                  port: http-metrics
                initialDelaySeconds: 45
              readinessProbe:
                httpGet:
                  path: /ready
                  port: http-metrics
                initialDelaySeconds: 45
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 100m
                  memory: 512Mi                
              securityContext:
                readOnlyRootFilesystem: true
              env:
                - name: JAEGER_AGENT_HOST
                  value: ""
          nodeSelector:
            {}
            
          affinity:
            {}
            
          tolerations:
            []
            
          terminationGracePeriodSeconds: 30
          volumes:
            - name: config
              secret:
                secretName: ${LOKI_SERVICE_NAME}
            - name: storage
              emptyDir: {}
parameters:
  - name: LOKI_SERVICE_NAME
    required: false
    value: loki