{{- range .Values.importer.prismJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wally-prism-{{ .datasetName | replace "_" "-" | lower }}-{{ $.Release.Revision }}-{{ randAlphaNum 5 | lower }}
  labels:
    component: importer
    job: prism-{{ .datasetName | replace "_" "-" | lower }}
    name: wally-prism-{{ .datasetName | replace "_" "-" | lower }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  backoffLimit: 3
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: wally-prism-{{ .datasetName | replace "_" "-" | lower }}
    spec:
      containers:
      - name: importer
        image: "{{ $.Values.importer.image }}"
        command: ['/dataload/load_prism.sh']
        args: ['{{ .datasetName }}']
        resources:
          requests:
            cpu: 200m
            memory: 4Gi
          limits:
            cpu: '1'
            memory: 4Gi
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.PGSuperUser" $ }}
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.PGSuperUser" $ }}
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.PGApplicationUser" $ }}
              key: dbname
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: {{ include "backend.PGSuperUser" $ }}
              key: host
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: minioAccessKey
              name: minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: minioSecretKey
              name: minio
        - name: MINIO_HOST_URL
          value: "{{ $.Values.importer.minioHostUrl }}"
      restartPolicy: Never
---
{{- end }}