apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-gatekeeper
  labels:
    app: {{ .Release.Name }}
    component: authentication
spec:
  host: {{ .Values.gatekeeper.host | quote }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Release.Name }}-gatekeeper
    weight: 100
  wildcardPolicy: None