apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gatekeeper
  labels:
    app: {{ .Release.Name }}
    component: authentication
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
    component: authentication
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  sessionAffinity: None