name: Build Importer Image
on:
  push:
    branches: [WO-2026-030-import-staging]
  workflow_dispatch:

permissions: {}

jobs:
  builds:
    name: Build Matrix
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [imports]
    timeout-minutes: 30
    steps:
      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: bcgov/action-builder-ghcr@v4.0.0
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tags: latest