name: "Openshift - Test Authentication - Tools Namespace"

on:
  push:
    branches:
        - WO-2026-030-repo-config
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  login:
    name: Login Only
    runs-on: ubuntu-24.04
    steps:
      - uses: bcgov/action-oc-runner@v1.2.2
        with:
          oc_namespace: ${{ secrets.OC_TOOLS_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOOLS_TOKEN }}